name:                accelerate-ad
version:             0.1.0.0
github:              "ajknapp/accelerate-ad"
license:             BSD3
author:              "Andrew Knapp"
maintainer:          "andy.j.knapp@gmail.com"
copyright:           "2018 Andrew Knapp"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Combinatory automatic differentiation in Haskell for heterogeneous computing. 

dependencies:
- base >= 4.7 && < 5
- accelerate >= 1.3 && < 1.4
- constraints
- deepseq

library:
  source-dirs: src

# executables:
  # accelerate-ad-exe:
  #   main:                Main.hs
  #   source-dirs:         app
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - accelerate-ad

tests:
  accelerate-ad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accelerate-ad
